version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - /data/app-data/wordpress/mysql:/var/lib/mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: thitruot103
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: domina
      MYSQL_PASSWORD: 12345aA@
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports: 
      - '20000:80'
    restart: always
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: domina
      WORDPRESS_DB_PASSWORD: 12345aA@
      WORDPRESS_DB_NAME: wordpress_db
