version: '3'
services:
  mysql:
    image: mysql:latest
    volumes:
      - /wordpress/mysql:/data/app-data/wordpress/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thitruot103
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: domina
      MYSQL_PASSWORD: 12345aA@
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    port: 
      - '20000:20000'
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: domina
      WORDPRESS_DB_PASSWORD: 12345aA@
    volumes:
      - /wordpress:/data/app-data/wordpress  
